---
- name: Install dependencies for HTTPS repositories
  apt:
    name:
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Add NodeSource GPG key
  shell: |
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource.gpg
  args:
    creates: /usr/share/keyrings/nodesource.gpg

- name: Add Node.js repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ nodejs_version }} nodistro main"
    state: present
    update_cache: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: present
